#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=3700
#SBATCH --time=14-00:00:0
#SBATCH --partition=xlong
#SBATCH --gres=gpu:L40:1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jingchao.peng@warwick.ac.uk

source /networkhome/WMGDS/peng_j/miniconda3/bin/activate
conda activate benchmark

python train_DFNet_update_temperature.py -opt options/train/ExpandNet_DFNet.yml